const exams = [
    // productExamCategory
    /*
    { id: 41, code: "SIE", name: "Securities Industry Essentials Examination", category: "productExamCategory" },
    { id: 42, code: "Series 79", name: "Investment Banking Registered Representative Examination", category: "productExamCategory" },
    { id: 43, code: "Series 22TO", name: "Direct Participation Programs Representative Examination", category: "productExamCategory" },
    { id: 44, code: "Series 38", name: "Canada Module of the General Securities Registered Representative (Without Options Questions)", category: "productExamCategory" },
    { id: 45, code: "Series 15", name: "Foreign Currency Options Examination", category: "productExamCategory" },
    { id: 46, code: "PC", name: "AMEX Put and Call Exam", category: "productExamCategory" },
    { id: 47, code: "Series 16", name: "NYSE Supervisory Analyst Examination", category: "productExamCategory" },
    { id: 49, code: "Series 82TO", name: "Limited Representative-Private Securities Offerings", category: "productExamCategory" },
    { id: 50, code: "Series 62", name: "Corporate Securities Limited Representative Examination", category: "productExamCategory" },
    { id: 51, code: "V06", name: "Variable Annuities Module Examination", category: "productExamCategory" },
    { id: 53, code: "Series 57TO", name: "Securities Trader Exam", category: "productExamCategory" },
    { id: 56, code: "Series 5", name: "Interest Rate Options Examination", category: "productExamCategory" },
    { id: 58, code: "Series 42", name: "Registered Options Representative Examination", category: "productExamCategory" },
    { id: 59, code: "Series 55", name: "Limited Representative-Equity Trader Exam", category: "productExamCategory" },
    { id: 60, code: "Series 000", name: "General Securities Principal Examination", category: "productExamCategory" },
    { id: 61, code: "Series 32", name: "Limited Futures Exam-Regulation", category: "productExamCategory" },
    { id: 62, code: "Series 46", name: "PCX Market Maker acting as a Floor Broker Exam", category: "productExamCategory" },
    { id: 64, code: "Series 52", name: "Municipal Securities Representative Examination", category: "productExamCategory" },
    { id: 66, code: "Series 57", name: "Securities Trader Exam", category: "productExamCategory" },
    { id: 67, code: "Series 79TO", name: "Investment Banking Registered Representative Examination", category: "productExamCategory" },
    { id: 69, code: "Series 34", name: "Retail Off-Exchange FOREX Examination", category: "productExamCategory" },
    { id: 70, code: "Series 87", name: "Research Analyst Exam - Part II Regulations Module", category: "productExamCategory" },
    */
    { id: 71, code: "Series 7", name: "General Securities Representative Examination", category: "productExamCategory" },
    /*
    { id: 73, code: "Series 48", name: "AMEX Market Maker Exam", category: "productExamCategory" },
    { id: 76, code: "Series 56", name: "Proprietary Trader Qualification Examination", category: "productExamCategory" },
    { id: 77, code: "Series 44", name: "PCX Market Maker Exam", category: "productExamCategory" },
    { id: 78, code: "Series 37", name: "Canada Module of the General Securities Registered Representative (With Options Questions)", category: "productExamCategory" },
    { id: 79, code: "Series 19", name: "NYSE Floor Clerk - Equities Examination", category: "productExamCategory" },
    { id: 80, code: "Series 99TO", name: "Operations Professional Examination", category: "productExamCategory" },
    { id: 81, code: "Series 31", name: "Futures Managed Funds Examination", category: "productExamCategory" },
    { id: 82, code: "Series 6TO", name: "Investment Company Products/Variable Contracts Representative Examination", category: "productExamCategory" },
    { id: 83, code: "Series 33", name: "Financial Instruments Examination", category: "productExamCategory" },
    { id: 84, code: "Series 6", name: "Investment Company Products/Variable Contracts Representative Examination", category: "productExamCategory" },
    { id: 85, code: "Series 82", name: "Limited Representative-Private Securities Offerings", category: "productExamCategory" },
    { id: 87, code: "Series 17", name: "Limited Registered Representative Examination", category: "productExamCategory" },
    { id: 88, code: "Series 45", name: "PCX Floor Broker Exam", category: "productExamCategory" },
    { id: 90, code: "Series 7B", name: "Floor Broker Examination", category: "productExamCategory" },
    { id: 91, code: "Series 11", name: "Assistant Representative-Order Processing Qualification Exam", category: "productExamCategory" },
    { id: 92, code: "Series 1", name: "Registered Representative Examination", category: "productExamCategory" },
    { id: 93, code: "Series 7A", name: "Floor Broker Representative Exam", category: "productExamCategory" },
    { id: 97, code: "Series 18", name: "Securities Industry Rules and Regulations Examination", category: "productExamCategory" },
    { id: 101, code: "Series 21", name: "NYSE Front Line Specialist Clerk", category: "productExamCategory" },
    { id: 102, code: "Series 7TO", name: "General Securities Representative Examination", category: "productExamCategory" },
    { id: 103, code: "Series 99", name: "Operations Professional Examination", category: "productExamCategory" },
    { id: 104, code: "Series 50", name: "Municipal Advisor Representative Qualification Exam", category: "productExamCategory" },
    { id: 105, code: "Series 72", name: "Government Securities Representative Examination", category: "productExamCategory" },
    { id: 106, code: "Series 86", name: "Research Analyst Exam - Part I Analysis Module", category: "productExamCategory" },
    { id: 107, code: "Series 52TO", name: "Municipal Securities Representative Examination", category: "productExamCategory" },
    { id: 109, code: "Series 25", name: "NYSE Trading Assistant Examination", category: "productExamCategory" },
    { id: 110, code: "Series 41", name: "NYSE Allied Member Examination", category: "productExamCategory" },
    { id: 111, code: "Series 3", name: "National Commodity Futures Examination", category: "productExamCategory" },
    { id: 114, code: "Series 22", name: "Direct Participation Programs Representative Examination", category: "productExamCategory" },
    { id: 115, code: "Series 2", name: "Non-Member General Securities Examination", category: "productExamCategory" },
  
    // principalExamCategory
    { id: 48, code: "Series 23", name: "General Securities Principal Sales Supervisor", category: "principalExamCategory" },
    { id: 52, code: "Series 24", name: "General Securities Principal Examination", category: "principalExamCategory" },
    { id: 54, code: "Series 51", name: "Municipal Fund Securities Principal Examination", category: "principalExamCategory" },
    { id: 55, code: "Series 8", name: "General  Securities Sales Supervisor Examination (Options Module & General Module)", category: "principalExamCategory" },
    { id: 57, code: "Series 27", name: "Financial and Operations Principal Examination", category: "principalExamCategory" },
    { id: 63, code: "Series 14", name: "Compliance Officer Examination", category: "principalExamCategory" },
    { id: 65, code: "Series 28", name: "Introducing Broker/Dealer Financial Operations Principal Examination", category: "principalExamCategory" },
    { id: 72, code: "Series 54", name: "Municipal Advisor Principal Qualification Examination", category: "principalExamCategory" },
    { id: 74, code: "Series 40", name: "Registered Principal Examination", category: "principalExamCategory" },
    { id: 86, code: "Series 12", name: "NYSE Branch Manager Examination", category: "principalExamCategory" },
    { id: 94, code: "F04", name: "Financial Principal Examination", category: "principalExamCategory" },
    { id: 95, code: "Series 39", name: "Direct Participation Programs Principal Examination", category: "principalExamCategory" },
    { id: 96, code: "Series 9", name: "General Securities Sales Supervisor - Options Module Examination", category: "principalExamCategory" },
    { id: 98, code: "Series 10", name: "General Securities Sales Supervisor - General Module Examination", category: "principalExamCategory" },
    { id: 99, code: "Series 4", name: "Registered Options Principal Examination", category: "principalExamCategory" },
    { id: 100, code: "Series 26", name: "Investment Company Products/Variable Contracts Principal Examination", category: "principalExamCategory" },
    { id: 108, code: "Series 53", name: "Municipal Securities Principal Examination", category: "principalExamCategory" },
    { id: 112, code: "Series 30", name: "NFA Branch Manager Examination", category: "principalExamCategory" },
    { id: 113, code: "Series 00", name: "General Securities Principal Examination", category: "principalExamCategory" },
    { id: 116, code: "Series 14A", name: "Compliance Official Specialist Exam", category: "principalExamCategory" },
    { id: 117, code: "Series 54FN", name: "Municipal Securities Financial and Operations Principal Examination", category: "principalExamCategory" },
  
    // stateExamCategory
    */
    { id: 68, code: "Series 63", name: "Uniform Securities Agent State Law Examination", category: "stateExamCategory" },
    { id: 89, code: "Series 65", name: "Uniform Investment Adviser Law Examination", category: "stateExamCategory" },
    { id: 75, code: "Series 66", name: "Uniform Combined State Law Examination", category: "stateExamCategory" },
];
  
  
  
  export { exams }